### ISSUE TITLE
Stable commit?

### ISSUE THREAD

**Issue by bhepple** [fejfighter/emacs#1]
Hi. I'd like to try this out and ultimately make it available as a Fedora package via the informal COPR repository - until the mainstream release catches up. I have already packaged a dozen or so other packages for sway on Fedora and would very much like to get PureGtk working.

I found some problems with today's bae4700 and wondered if there is a stable, working commit that I can use? Or should I use masm11's repo for now?

The issue I had was on startup, it complained about illegal byte-code when loading use-package. I had removed all traces of the official Fedora emacs and all .elc in my .emacs.d so I decided I was looking at an unstable commit.

**Comment by bhepple** [comment]
I fixed the byte-compile problem by re-installing use-package from melpa but my question remains - or perhaps I should rephrase - is it too soon to be providing beta-test packages for people?

**Comment by A6GibKm** [comment]
Maybe the issue was in your `~/.emacs.d` folder? The melpa issue sounds as if the binaries were not compatible, I have a similar issue with Doom emacs and the pgtk+native-comp build, but re building solves the issue.

**Comment by bhepple** [comment]
That's exactly what I found - I fixed it by re-installing 'use-package' - it may have been that -26 was more tolerant of the 'bad package but emacs-pgtk was not - perhaps the -27 code? Dunno, but all good now.

**Comment by fejfighter** [comment]
Apologies for not seeing this earlier, apparently I need to star and watch my own repos for notifications/ email.

I cannot remember any major issues from that time, but I had/have a newborn around, so it's entirely possible I forgot

I do try to run each commit as I push them with my config hosted here, although admittedly local install and flatpak on my laptop, but there are build/ load issues on flatpak.

the Masm11 repo should be identical to my `upstream-rebase' branch excepting some variation upstream commits, but we have checked for diversion of code in the branch a few times

I appreciate the COPR build you're doing I'd probably use them myself if I didn't have the source laying around.

Hopefully now if more issues come up I will see notifications earlier

**Comment by A6GibKm** [comment]
I have this one running: https://copr.fedorainfracloud.org/coprs/deathwish/emacs-pgtk-nativecomp/

While I don't need stable commits, as long as you keep rebasing masm11's onto the native-comp branch (or updating the branch `pgtk-nativecomp`) *relatively often*, we are all happy. Thanks for maintaining this repo :+1:

**Comment by fejfighter** [comment]
No problems, I do try to do them once every few days, new pgtk/upstream rebase has just gone up

**Comment by bhepple** [comment]
I'm deferring to the https://copr.fedorainfracloud.org/coprs/deathwish/emacs-pgtk-nativecomp/ build (as it is also nativecomp)

Thanks to all you guys pushing the emacs envelope. Loving your work!!

**Comment by A6GibKm** [comment]
@fejfighter thanks, but no need to overdo it, every ~15 days is good enough. Specially considering they have made big changes (broken the rpm spec at least 4 times) on nativecomp recently.

**Comment by fejfighter** [comment]
Native comp has been merged, pgtk is on a branch on savannah with motions to get it merged, anything I managed to get polished for it usually gets sent in immediately so this can probably be closed
